// Tier B — soft comfort (occasional)
// Gentle reassurance, used sparingly
const tierB = [
  "you are doing okay",
  "quiet is allowed",
  "it's fine to rest here",
  "you don't have to figure it out today",
  "it's okay to not have answers",
  "you are allowed to feel what you feel",
  "gentle things take time",
  "you deserve quiet moments",
  "you can let your shoulders drop",
  "it's okay if today is small",
  "you can sit with this feeling",
  "you don't have to be productive",
  "rest is allowed",
  "you can be gentle with yourself",
  "you can stop trying for a moment",
  "it's okay to just exist",
  "you can let go a little",
  "it's okay to slow down",
  "you don't need permission to rest",
  "you can stop holding everything",
  "it's fine to just be",
  "you are allowed to pause here",
  "it's okay to be quiet inside",
  "you can soften your thoughts",
  "it's fine to stay here awhile",
  "you can stop performing",
  "this counts as resting",
  "it's okay to do nothing impressively",
  "you are not behind",
  "this is still progress",
  "you can take today lightly",
  "you are allowed to arrive slowly",
  "this does not need effort",
  "you can ease up a little",
  "it's okay to feel unfinished",
  "you can be imperfect here",
  "you are not doing this wrong",
  "this moment does not judge you",
  "you can be softer with yourself",
  "nothing about you needs fixing",
  "you can take a break from managing",
  "it's okay to feel unprepared",
  "you don't need to prove anything",
  "you can stay gentle with today",
  "this is enough care for now",
  "you are allowed to be uncertain",
  "you can rest without explaining",
  "this moment can hold you",
  "you don't have to optimize yourself",
  "it's okay to move without clarity",
  "you can leave things unfinished",
  "this does not require strength"
];
