// Tier D — ending (locked)
// Final messages, shown once, disable button
const tierD = [
  "okay, that's enough",
  "we can stop now",
  "that's all for now",
  "the page is resting now",
  "thank you for being here",
  "this was a small moment together",
  "you can go gently now",
  "this pause is complete",
  "nothing else is needed",
  "we can stop here",
  "it's okay to leave now",
  "see you another time",
   "that’s it",
  "we’re done here",
  "this is the end",
  "nothing more will happen",
  "this stops now",
  "the moment has passed",
  "this is complete",
  "the page has finished",
  "time to close this",
  "this concludes things",
  "no more messages",
  "this has ended",
  "the pause is over",
  "this is where it ends",
  "everything stops here"
];
