// Tier C — light absurd (rare)
// Whimsical, never consecutive, feels like a gift
const tierC = [
  "somewhere, a cat is sleeping",
  "this sentence is just sitting here",
  "imagine a very calm cloud",
  "a tree is just standing there, being a tree",
  "this message has no agenda",
  "pretend this is a windowsill",
  "everything is fine in a small way",
  "you can exist like a houseplant",
  "this moment is softly weird",
  "somewhere, a chair is doing its job",
  "a plant is not thinking about anything",
  "this moment does not know you are here",
  "a window is being a window",
  "nothing in this sentence wants anything",
  "a sock somewhere has lost its pair",
  "this message is passing through",
  "a cloud is minding its own business",
  "a cup is waiting patiently",
  "this thought arrived without instructions",
  "something nearby is completely neutral",
  "a hallway exists even when empty",
  "this sentence will end soon",
  "a cat has forgotten what time it is",
  "a ceiling is holding steady",
  "this moment is not impressive",
  "a shadow is doing its thing",
  "a door is neither open nor closed",
  "this message is not urgent",
  "a lamp is quietly lamping",
  "nothing here is symbolic",
  "a plant leaned slightly, for no reason",
  "this sentence does not continue",
  "a bench is waiting for no one",
  "a cloud changed shape and moved on",
  "this thought does not repeat itself",
  "a corner exists somewhere nearby",
  "nothing in this moment is remarkable",
  "a room is holding its shape",
  "this message has already happened",
  "a cat blinked and forgot why",
  "a window reflected something unimportant",
  "this sentence has no follow-up",
  "a plant survived the afternoon",
  "nothing here is a metaphor",
  "a wall is being dependable",
  "this moment does not need context",
  "a clock kept going without comment",
  "this thought is lightly unfinished",
  "a ceiling fan is thinking about nothing",
  "nothing in this sentence matters much",
  "a chair did not move",
  "this message is mildly unnecessary",
  "a tree did not notice you",
  "this moment is barely a moment",
  "something nearby is perfectly ordinary",
  "this sentence is not trying",
  "a cloud forgot its previous shape",
  "nothing here is asking anything"
];
